version: 2

defaults: &defaults
  docker:
    - image: circleci/node:8

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm test
      - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> .npmrc
      - persist_to_workspace:
          root: ~/project
          paths:
            - dist/
            - .npmrc
  deploy:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - run: npm publish

  deploy-beta:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - run: npm publish --tag beta

workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - deploy:
          requires:
            - build
          filters:
            tags:
              only: /release-[0-9]+\.[0-9]+\.[0-9]+/
            branches:
              ignore: /.*/
      - deploy-beta:
          requires:
            - build
          filters:
            tags:
              only: /beta-[0-9]+\.[0-9]+\.[0-9]+/
            branches:
              ignore: /.*/
